pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        mvn clean install
      }
    }
//My change
//     stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        npm install
      }
    }
  }
}